spring:
  application:
    name: bulletin-board

  datasource:
    url: jdbc:postgresql://localhost:5432/board
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/board-realm

keycloak:
  admin:
    server-url: ${KEYCLOAK_BASE_URL:http://localhost:8081}
    realm: ${KEYCLOAK_REALM:board-realm}
    token-realm: ${KEYCLOAK_TOKEN_REALM:${KEYCLOAK_REALM:board-realm}}
    client-id: ${KEYCLOAK_CLIENT_ID:admin-cli}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:}
    username: ${KEYCLOAK_ADMIN:}
    password: ${KEYCLOAK_ADMIN_PASSWORD:}

server:
  port: 9090
