spring:
  application:
    name: bulletin-board
  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:${KEYCLOAK_BASE_URL:http://localhost:8081}/realms/${KEYCLOAK_REALM:board-realm}}

keycloak:
  admin:
    server-url: ${KEYCLOAK_BASE_URL:http://localhost:8081}
    realm: ${KEYCLOAK_REALM:board-realm}
    token-realm: ${KEYCLOAK_TOKEN_REALM:${KEYCLOAK_REALM:board-realm}}
    client-id: ${KEYCLOAK_CLIENT_ID:board-backend}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:Qd5eK8Yy4YgwHtkRaZ4sOtra4m7eK6JI}
    username: ${KEYCLOAK_ADMIN:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

server:
  port: ${SERVER_PORT:9090}
